import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { discoverProjects, derive, normalizeUsage, tokenActivity, capabilityUsageEvents, CONFIDENCE } from '../src/core.js';
import { shareableStack, manifest, createSnapshot, shareCardSvg } from '../src/sharing.js';

function fixture() { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'aidash-')); fs.mkdirSync(path.join(root, 'alpha', '.git'), { recursive: true }); fs.writeFileSync(path.join(root, 'alpha', 'app.js'), 'export const answer = 42;\n'); return root; }
test('discovers a canonical Git project', () => { const root = fixture(); const projects = discoverProjects(root); assert.equal(projects.length, 1); assert.equal(projects[0].name, 'alpha'); assert.equal(projects[0].confidence, CONFIDENCE.confirmed); });
test('separates cache token fields from fresh input and output', () => { const t=normalizeUsage({usage:{input_tokens:10,output_tokens:5,cache_read_input_tokens:100,cache_creation_input_tokens:20}}); assert.deepEqual(t,{freshInput:10,output:5,cacheRead:100,cacheCreation:20,reasoning:0,other:0}); assert.equal(tokenActivity(t),135); });
test('headline project analytics exclude unknown attribution', () => { const root = fixture(), project=discoverProjects(root)[0]; const s=(id,projectId,confidence)=>({id,agent:'Claude',projectId,timestamp:'2026-08-10T00:00:00Z',tokens:{freshInput:10,output:5,cacheRead:0,cacheCreation:0,reasoning:0,other:0},tools:1,compactions:0,attributionConfidence:confidence}); const r=derive({projects:[project],capabilities:[],capabilityUsageEvents:[],errors:[],sources:{},sessions:[s('a',project.id,CONFIDENCE.confirmed),s('b',null,CONFIDENCE.unknown)]}); assert.equal(r.projects[0].sessionCount,1); assert.equal(r.summary.sessions,2); });
test('structured capability evidence becomes a confirmed compact event',()=>{const cap={id:'c1',capabilityKey:'graphify',name:'graphify'},session={id:'Claude:1',projectId:'p1',timestamp:'2026-08-01T00:00:00Z'};const events=capabilityUsageEvents([{sessionId:'Claude:1',skill:'graphify',timestamp:session.timestamp,sourceFile:'/private'}],[cap],[session]);assert.equal(events.length,1);assert.equal(events[0].confidence,CONFIDENCE.confirmed);assert.equal(events[0].contextLabel,'graphify workflow');});
test('public stack excludes private capabilities and paths',()=>{const index={summary:{agents:['Claude'],tokens:{freshInput:1,output:2},sessions:1,activeProjects:1,capabilityUses:0},sessions:[],efficiency:{components:{tokensPerSession:{comparable:false}},period:{}},capabilities:[{name:'Public',type:'Agent Skill',origin:'Claude user',isPrivate:false,usageCount:0},{name:'Secret',type:'Agent Skill',origin:'Project',isPrivate:true,location:'/Users/name/secret',usageCount:0}]};assert.equal(shareableStack(index).capabilities.length,1);assert.equal(JSON.stringify(manifest(index)).includes('/Users/'),false);});
test('snapshot freezes selected values and cards honor requested dimensions',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'snap-'));const index={summary:{agents:['Claude'],tokens:{freshInput:20,output:2},sessions:4,activeProjects:2,capabilityUses:0},sessions:[{agent:'Claude'}],efficiency:{components:{tokensPerSession:{comparable:false}},period:{}},capabilities:[]};const snap=createSnapshot(index,['activeProjects'],'9:16',dir);assert.equal(snap.metrics[0].value,2);assert.match(shareCardSvg(snap),/width="1080" height="1920"/);});
