import os from 'node:os';
import { execFileSync } from 'node:child_process';

export const AGENTS=['Claude','Codex','Cursor'];
export const ACTIVITY_WINDOW_MS=45_000;
export const ACTIVITY_SAMPLE_MS=1_000;
export const ACTIVITY_DECAY_MS=9_000;

const finite=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const timestamp=value=>{const n=new Date(value).getTime();return Number.isFinite(n)?n:null;};
export function activityEventWeight(event={}) { return 1+Math.min(2,Math.log2(Math.max(0,finite(event.tools))+1)); }
export function activityIntensityAt(events, agent, at, {decayMs=ACTIVITY_DECAY_MS}={}) { return events.filter(event=>event.agent===agent).reduce((total,event)=>{const age=at-timestamp(event.timestamp);if(!Number.isFinite(age)||age<0||age>decayMs*7)return total;return total+activityEventWeight(event)*Math.exp(-age/decayMs);},0); }
export function activitySeries(events, agent, now=Date.now(), {windowMs=ACTIVITY_WINDOW_MS,sampleMs=ACTIVITY_SAMPLE_MS,decayMs=ACTIVITY_DECAY_MS}={}) { const start=now-windowMs,points=[];for(let at=start;at<=now;at+=sampleMs)points.push({at,intensity:activityIntensityAt(events,agent,at,{decayMs})});return points; }
export function activityMonitor(events, now=Date.now()) { return AGENTS.map(agent=>{const series=activitySeries(events,agent,now),intensity=series.at(-1)?.intensity||0,lastAt=Math.max(...events.filter(event=>event.agent===agent).map(event=>timestamp(event.timestamp)||0),0);return {agent,intensity,lastObservedAt:lastAt?new Date(lastAt).toISOString():null,state:intensity>=.12?'Active':'Idle',series};}); }

const cpuTotals=cpus=>cpus.reduce((out,cpu)=>{for(const [name,value] of Object.entries(cpu.times||{}))out[name]=(out[name]||0)+finite(value);return out;},{});
export function cpuUtilization(previous=[],current=[]) { const a=cpuTotals(previous),b=cpuTotals(current),total=Math.max(0,Object.values(b).reduce((x,y)=>x+y,0)-Object.values(a).reduce((x,y)=>x+y,0)),idle=Math.max(0,(b.idle||0)-(a.idle||0));return total?Math.max(0,Math.min(100,(total-idle)/total*100)):null; }
export function normalizeResources({totalMemory,freeMemory,ramUsed,cpuPercent,dashboardRss,dashboardCpuPercent}={}) { const total=Math.max(0,finite(totalMemory)),free=Math.max(0,finite(freeMemory)),used=Math.max(0,Number.isFinite(ramUsed)?ramUsed:total-free);return {ram:{used,total,ratio:total?used/total:null},cpuPercent:Number.isFinite(cpuPercent)?Math.max(0,Math.min(100,cpuPercent)):null,dashboard:{rss:Math.max(0,finite(dashboardRss)),cpuPercent:Number.isFinite(dashboardCpuPercent)?Math.max(0,dashboardCpuPercent):null}}; }
export function macWorkingMemory() { if(process.platform!=='darwin')return null;try{const text=execFileSync('vm_stat',[],{encoding:'utf8',timeout:1500,stdio:['ignore','pipe','ignore']}),pageSize=Number(text.match(/page size of (\d+) bytes/)?.[1]),pages=name=>Number(text.match(new RegExp(`Pages ${name}:\\s+(\\d+)\\.`))?.[1]||0);if(!pageSize)return null;return (pages('active')+pages('wired down')+pages('occupied by compressor'))*pageSize;}catch{return null;} }
export function createSystemSampler(deps={}) { const cpus=deps.cpus||os.cpus,totalmem=deps.totalmem||os.totalmem,freemem=deps.freemem||os.freemem,processUsage=deps.processUsage||process.cpuUsage,processMemory=deps.processMemory||process.memoryUsage,workingMemory=deps.workingMemory||macWorkingMemory,now=deps.now||Date.now;let priorCpus=cpus(),priorCpu=processUsage(),priorAt=now(),lastWorkingMemory=workingMemory(),lastMemoryAt=priorAt,last=normalizeResources({totalMemory:totalmem(),freeMemory:freemem(),ramUsed:lastWorkingMemory,dashboardRss:processMemory().rss});return ()=>{const currentCpus=cpus(),currentCpu=processUsage(),at=now(),elapsed=Math.max(1,at-priorAt)*1000,cpuPercent=cpuUtilization(priorCpus,currentCpus),dashboardCpuPercent=((currentCpu.user+currentCpu.system-priorCpu.user-priorCpu.system)/elapsed)*100;if(at-lastMemoryAt>=30_000){lastWorkingMemory=workingMemory();lastMemoryAt=at;}last={...normalizeResources({totalMemory:totalmem(),freeMemory:freemem(),ramUsed:lastWorkingMemory,cpuPercent,dashboardRss:processMemory().rss,dashboardCpuPercent}),sampledAt:new Date(at).toISOString()};priorCpus=currentCpus;priorCpu=currentCpu;priorAt=at;return last;}; }
