import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { fileURLToPath } from 'node:url';
import { defaultSources, scan, applyProjectMetadata, PROJECT_STATUSES } from './core.js';
import { createSystemSampler, liveStateSnapshot, sessionFileSignal } from './activity.js';
import { readPlanCapacity } from './capacity.js';
import { shareableStack, manifest, privateInventory, publicMetricOptions, createSnapshot, shareCardSvg, setupPrompt } from './sharing.js';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dataDir = path.join(root, '.dashboard-data'); const indexFile = path.join(dataDir, 'index.json'); const projectMetaFile=path.join(dataDir,'project-metadata.json');
let liveIndex = null, lastReason = 'starting'; let refreshing = false; const sampleSystem=createSystemSampler(); let latestSystem=sampleSystem(),latestCapacity=readPlanCapacity(); const liveActivityEvents=[],liveFileSizes=new Map(),liveFiles=new Map();
function projectMetadata(){try{return JSON.parse(fs.readFileSync(projectMetaFile,'utf8'));}catch{return {version:1,projects:{}};}}
function saveProjectMetadata(metadata){fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(projectMetaFile,JSON.stringify(metadata,null,2));}
function decorate(result){return applyProjectMetadata(result,projectMetadata());}
function refresh(reason = 'manual') { if (refreshing) return liveIndex; refreshing = true; fs.mkdirSync(dataDir, { recursive: true }); const previous = liveIndex || (fs.existsSync(indexFile) ? JSON.parse(fs.readFileSync(indexFile, 'utf8')) : null); const result = scan(defaultSources(), previous); result.summary.refreshReason = reason; fs.writeFileSync(indexFile, JSON.stringify(result, null, 2)); liveIndex = decorate(result); refreshing = false; return liveIndex; }
function index() { return liveIndex || (fs.existsSync(indexFile) ? (liveIndex = decorate(JSON.parse(fs.readFileSync(indexFile, 'utf8')))) : refresh('startup')); }
function body(req) { return new Promise((resolve) => { let text=''; req.on('data',d=>text+=d); req.on('end',()=>{ try { resolve(JSON.parse(text||'{}')); } catch { resolve({}); } }); }); }
function contentType(file) { return file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : file.endsWith('.html') ? 'text/html' : 'application/json'; }
function rememberLiveFiles(agent, root, depth=0) { if(depth>5)return; let entries=[];try{entries=fs.readdirSync(root,{withFileTypes:true});}catch{return;}for(const entry of entries){const file=path.join(root,entry.name),normal=file.replace(/\\/g,'/');if(entry.isDirectory()){if(!['.git','node_modules','.dashboard-data'].includes(entry.name))rememberLiveFiles(agent,file,depth+1);continue;}if(!/\.(jsonl|json)$/i.test(entry.name)||(agent==='Cursor'&&!normal.includes('/agent-transcripts/')))continue;try{const stat=fs.statSync(file);liveFiles.set(file,agent);liveFileSizes.set(file,{size:stat.size,mtimeMs:stat.mtimeMs});}catch{}}}
function recordLiveActivity(agent, source, filename) { const candidate=filename?path.resolve(source,String(filename)):null,normal=(candidate||'').replace(/\\/g,'/'); if(agent&&candidate&&(!/\.(jsonl|json)$/i.test(candidate)||(agent==='Cursor'&&!normal.includes('/agent-transcripts/'))))return; const previous=liveFileSizes.get(candidate),next=candidate?(()=>{try{const stat=fs.statSync(candidate);return {size:stat.size,mtimeMs:stat.mtimeMs};}catch{return null;}})():null;if(candidate&&next&&previous&&next.size===previous.size&&next.mtimeMs===previous.mtimeMs)return;const signal=sessionFileSignal({agent,timestamp:Date.now(),previousSize:previous?.size??next?.size??0,size:next?.size??previous?.size??0,kind:candidate?'session-file-update':'source-directory-update'}); if(candidate&&next!=null){liveFiles.set(candidate,agent);liveFileSizes.set(candidate,next);} if(!signal)return; const mostRecent=liveActivityEvents.at(-1); if(mostRecent?.agent===signal.agent&&mostRecent.kind===signal.kind&&Date.now()-new Date(mostRecent.timestamp).getTime()<350){liveActivityEvents[liveActivityEvents.length-1]=signal;}else liveActivityEvents.push(signal); const cutoff=Date.now()-60_000; while(liveActivityEvents[0]&&new Date(liveActivityEvents[0].timestamp).getTime()<cutoff)liveActivityEvents.shift(); }
function pollLiveFiles(){for(const [file,agent]of liveFiles)recordLiveActivity(agent,path.dirname(file),path.basename(file));}
function watchSources() { const sources=defaultSources(),sourceAgents={claudeRoot:'Claude',codexRoot:'Codex',cursorRoot:'Cursor'}, entries=Object.entries(sources); let timer; const ignored=/(^|[\\/])(\.dashboard-data|\.git|node_modules)([\\/]|$)/; const changed=(key,source,filename)=>{const candidate=filename?path.resolve(source,String(filename)):'';if((candidate&&(candidate===dataDir||candidate.startsWith(`${dataDir}${path.sep}`)))||ignored.test(candidate))return;if(sourceAgents[key]){recordLiveActivity(sourceAgents[key],source,filename);return;}clearTimeout(timer);timer=setTimeout(()=>refresh('project source change'),7_500);}; for(const [key,source] of entries)try{fs.watch(source,{recursive:true},(_event,filename)=>changed(key,source,filename));}catch{try{fs.watch(source,(_event,filename)=>changed(key,source,filename));}catch{}}setInterval(()=>refresh('periodic check'),300000).unref();}
function liveState(){return liveStateSnapshot({system:latestSystem,events:liveActivityEvents,capacity:latestCapacity});}
function serve() { refresh('startup'); const sources=defaultSources();rememberLiveFiles('Claude',sources.claudeRoot);rememberLiveFiles('Codex',sources.codexRoot);rememberLiveFiles('Cursor',sources.cursorRoot);watchSources(); setInterval(()=>{latestSystem=sampleSystem();},2_000).unref();setInterval(pollLiveFiles,1_500).unref();setInterval(()=>{latestCapacity=readPlanCapacity();},60_000).unref(); const publicDir = path.join(root, 'public'); const server = http.createServer(async (req, res) => { const url = new URL(req.url, 'http://localhost');
  if (url.pathname === '/api/data') { res.setHeader('Content-Type', 'application/json'); return res.end(JSON.stringify(index())); }
  if (url.pathname === '/api/scan' && req.method === 'POST') { res.setHeader('Content-Type', 'application/json'); return res.end(JSON.stringify(refresh('manual refresh'))); }
  if (url.pathname === '/api/status') { res.setHeader('Content-Type','application/json'); const x=index(); return res.end(JSON.stringify({state:'Live',lastUpdated:x.summary.lastScanAt,reason:x.summary.refreshReason||lastReason,diagnostics:x.summary.diagnostics})); }
  if (url.pathname === '/api/live-state') { res.setHeader('Content-Type','application/json'); res.setHeader('Cache-Control','no-store, max-age=0'); return res.end(JSON.stringify(liveState())); }
  if (url.pathname === '/api/live') { res.setHeader('Content-Type','application/json'); res.setHeader('Cache-Control','no-store, max-age=0'); return res.end(JSON.stringify(liveState().activity)); }
  if (url.pathname === '/api/system') { res.setHeader('Content-Type','application/json'); res.setHeader('Cache-Control','no-store, max-age=0'); return res.end(JSON.stringify(latestSystem)); }
  if (url.pathname === '/api/export/stack') { res.setHeader('Content-Type','application/json'); return res.end(JSON.stringify(shareableStack(index()),null,2)); }
  if (url.pathname === '/api/export/manifest') { res.setHeader('Content-Type','application/json'); return res.end(JSON.stringify(manifest(index()),null,2)); }
  if (url.pathname === '/api/export/private') { res.setHeader('Content-Type','application/json'); return res.end(JSON.stringify(privateInventory(index()),null,2)); }
  if (url.pathname === '/api/export/setup-prompt') { res.setHeader('Content-Type','text/plain; charset=utf-8'); return res.end(setupPrompt(index())); }
  if (url.pathname === '/api/share/options') { res.setHeader('Content-Type','application/json'); return res.end(JSON.stringify(publicMetricOptions(index(),url.searchParams.get('period')||'month'))); }
  if (url.pathname === '/api/share/snapshot' && req.method === 'POST') { const b=await body(req); try { const snapshot=createSnapshot(index(),b.metrics,b.format,path.join(dataDir,'snapshots'),b.period||'month'); res.setHeader('Content-Type','application/json'); return res.end(JSON.stringify(snapshot)); } catch(e) { res.statusCode=400; return res.end(JSON.stringify({error:e.message})); } }
  if (url.pathname === '/api/share/card.svg') { const id=url.searchParams.get('snapshot'); const file=id&&path.join(dataDir,'snapshots',`${id}.json`); if(!file || !fs.existsSync(file)){res.statusCode=404;return res.end('Snapshot not found');} res.setHeader('Content-Type','image/svg+xml'); return res.end(shareCardSvg(JSON.parse(fs.readFileSync(file,'utf8')))); }
  const metaMatch=url.pathname.match(/^\/api\/projects\/([^/]+)\/metadata$/);
  if(metaMatch && req.method==='POST'){const id=decodeURIComponent(metaMatch[1]),b=await body(req),known=index().projects.find(p=>p.id===id);if(!known){res.statusCode=404;return res.end(JSON.stringify({error:'Project not found'}));}const metadata=projectMetadata(),current=metadata.projects[id]||{},next={...current,pinned:typeof b.pinned==='boolean'?b.pinned:Boolean(current.pinned),status:PROJECT_STATUSES.includes(b.status)?b.status:(b.status===null?null:current.status||null),note:typeof b.note==='string'?b.note.slice(0,500):current.note||'',canonicalPath:known.canonicalPath};if(!next.pinned&&!next.status&&!next.note)delete metadata.projects[id];else metadata.projects[id]=next;saveProjectMetadata(metadata);liveIndex=decorate({...index(),summary:{...index().summary,lastScanAt:index().summary.lastScanAt}});res.setHeader('Content-Type','application/json');return res.end(JSON.stringify(liveIndex.projects.find(p=>p.id===id)));}
  let asset = url.pathname === '/' ? 'index.html' : url.pathname.replace(/^\//, ''); asset = path.normalize(asset); const full = path.join(publicDir, asset); if (!full.startsWith(publicDir) || !fs.existsSync(full)) { res.statusCode = 404; return res.end('Not found'); } res.setHeader('Content-Type', contentType(full)); res.end(fs.readFileSync(full));
 }); server.listen(4177, '127.0.0.1', () => console.log('AI Development Dashboard → http://127.0.0.1:4177'));
}
if (process.argv[2] === 'scan') { const data = refresh(); console.log(`Indexed ${data.projects.length} projects, ${data.sessions.length} sessions, ${data.capabilities.length} capabilities.`); } else serve();
