import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

export const CONFIDENCE = { confirmed: 'Confirmed', strong: 'Strongly inferred', weak: 'Weakly inferred', unknown: 'Unknown' };
export const METRIC_VERSION = '2.0';
const home = process.env.HOME;
const hash = (v) => crypto.createHash('sha256').update(String(v)).digest('hex').slice(0, 16);
const stat = (p) => { try { return fs.statSync(p); } catch { return null; } };
const fingerprint = (p) => { const s = stat(p); return s ? `${s.size}:${Math.round(s.mtimeMs)}` : null; };
const iso = (v) => { const d = new Date(v); return Number.isNaN(d.getTime()) ? null : d.toISOString(); };
const normal = (p) => path.resolve(p).replace(/\\/g, '/');
const within = (child, parent) => normal(child).startsWith(`${normal(parent)}/`) || normal(child) === normal(parent);
const git = (cwd, args) => { try { return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); } catch { return null; } };
function walk(root, { maxDepth = 7, maxFiles = Infinity, accept = () => true, ignore = [] } = {}) { const out = []; const ignored = new Set(['.git', 'node_modules', '.dashboard-data', 'archive', 'Archives', ...ignore]); function visit(dir, depth) { if (depth > maxDepth || out.length >= maxFiles) return; let es; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; } for (const e of es) { if (out.length >= maxFiles) return; const p = path.join(dir, e.name); if (e.isDirectory()) { if (!ignored.has(e.name)) visit(p, depth + 1); } else if (accept(p, e)) out.push(p); } } visit(root, 0); return out; }
// Bounded metadata parsing: no raw transcript is retained or loaded wholesale.
function readJsonlPrefix(file, onRow) { try { const size = stat(file)?.size || 0; const length = Math.min(size, 512 * 1024); const fd = fs.openSync(file, 'r'); const b = Buffer.alloc(length); fs.readSync(fd, b, 0, length, 0); fs.closeSync(fd); for (const line of b.toString('utf8').split('\n')) if (line.trim()) try { onRow(JSON.parse(line)); } catch {} } catch {} }
function gitProject(projects, cwd) { if (!cwd) return null; return projects.filter((p) => within(cwd, p.canonicalPath)).sort((a, b) => b.canonicalPath.length - a.canonicalPath.length)[0] || null; }
const emptyTokens = () => ({ freshInput: 0, output: 0, cacheRead: 0, cacheCreation: 0, reasoning: 0, other: 0 });
export function normalizeUsage(source = {}) { const u = source.usage || source.message?.usage || source.payload?.usage || {}; const n = (v) => Number.isFinite(Number(v)) ? Number(v) : 0; return { freshInput: n(u.input_tokens ?? u.inputTokens), output: n(u.output_tokens ?? u.outputTokens), cacheRead: n(u.cache_read_input_tokens ?? u.cacheReadInputTokens ?? u.cached_tokens), cacheCreation: n(u.cache_creation_input_tokens ?? u.cacheCreationInputTokens), reasoning: n(u.reasoning_tokens ?? u.reasoningTokens), other: n(u.other_tokens ?? u.otherTokens) }; }
export const tokenActivity = (t = emptyTokens()) => Object.values(t).reduce((a, n) => a + (Number(n) || 0), 0);
function addTokens(a, b = emptyTokens()) { for (const k of Object.keys(a)) a[k] += b[k] || 0; }
function encodedPath(p) { return normal(p).replace(/[^A-Za-z0-9]/g, '-'); }
function projectFromClaudeFolder(file, projects, root) { const top = path.relative(root, file).split(path.sep)[0]; return projects.find((p) => encodedPath(p.canonicalPath) === top) || null; }
function makeSession({ agent, id, file, timestamp, cwd, model, projects, confidence = CONFIDENCE.confirmed }) { const p = gitProject(projects, cwd); return { id: `${agent}:${id}`, agent, sourceFile: file, sourceFingerprint: fingerprint(file), timestamp: iso(timestamp), projectId: p?.id || null, projectPath: p?.canonicalPath || null, attributionConfidence: p ? confidence : CONFIDENCE.unknown, model: model || null, tokens: emptyTokens(), tools: 0, compactions: 0 }; }

export function discoverProjects(root) { const roots = new Set(); function visit(dir, depth = 0) { if (depth > 5) return; let es; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; } if (es.some((e) => e.name === '.git')) roots.add(dir); for (const e of es) if (e.isDirectory() && !['.git', 'node_modules', '.dashboard-data', 'Archives', 'archive'].includes(e.name)) visit(path.join(dir, e.name), depth + 1); } visit(root); return [...roots].sort().map((canonicalPath) => ({ id: `project:${hash(canonicalPath)}`, name: path.basename(canonicalPath), canonicalPath, git: { isRepository: true, branch: git(canonicalPath, ['branch', '--show-current']) || null, remote: git(canonicalPath, ['remote', 'get-url', 'origin']) || null, lastCommitAt: iso(git(canonicalPath, ['log', '-1', '--format=%cI'])) }, confidence: CONFIDENCE.confirmed })); }

export function scanClaude(projects, root = path.join(home, '.claude', 'projects'), previous = new Map()) { const sessions = new Map(); const skillSignals = []; let parsed = 0, inspected = 0, changed = 0; for (const file of walk(root, { maxDepth: 4, accept: (f) => f.endsWith('.jsonl') })) { inspected++; const prior = previous.get(file); if (prior?.sourceFingerprint === fingerprint(file)) { sessions.set(prior.id, prior); continue; } changed++; let event, best; readJsonlPrefix(file, (row) => { parsed++; const id = row.sessionId || path.basename(file, '.jsonl'); if (!event) event = makeSession({ agent: 'Claude', id, file, timestamp: row.timestamp, cwd: row.cwd, model: row.message?.model, projects }); const candidate = gitProject(projects, row.cwd); if (candidate && (!best || candidate.canonicalPath.length > best.canonicalPath.length)) best = candidate; addTokens(event.tokens, normalizeUsage(row)); if (row.type === 'assistant' && Array.isArray(row.message?.content)) event.tools += row.message.content.filter((x) => x.type === 'tool_use').length; if (row.isCompactSummary || row.compactMetadata || /compact|summary/i.test(row.type || '')) event.compactions++; if (row.timestamp && (!event.timestamp || row.timestamp > event.timestamp)) event.timestamp = iso(row.timestamp); if (row.attributionSkill) skillSignals.push({ sessionId: event.id, skill: String(row.attributionSkill), timestamp: iso(row.timestamp), cwd: row.cwd, sourceFile: file }); }); if (event) { const slugProject = projectFromClaudeFolder(file, projects, root); const selected = best || slugProject; if (selected) { event.projectId = selected.id; event.projectPath = selected.canonicalPath; event.attributionConfidence = best ? CONFIDENCE.confirmed : CONFIDENCE.strong; } sessions.set(event.id, event); } } return { sessions: [...sessions.values()], skillSignals, diagnostics: { claudeFilesInspected: inspected, claudeFilesChanged: changed, claudeRecordsParsed: parsed } }; }
export function scanCodex(projects, root = path.join(home, '.codex', 'sessions'), previous = new Map()) { const sessions = new Map(); let parsed = 0, inspected = 0, changed = 0; for (const file of walk(root, { maxDepth: 5, accept: (f) => f.endsWith('.jsonl') })) { inspected++; const prior = previous.get(file); if (prior?.sourceFingerprint === fingerprint(file)) { sessions.set(prior.id, prior); continue; } changed++; let event, best; readJsonlPrefix(file, (row) => { parsed++; const p = row.payload || {}; const id = p.id || p.session_id || p.sessionId || path.basename(file, '.jsonl'); const cwd = p.cwd || p.working_directory || p.workspace?.cwd; if (!event) event = makeSession({ agent: 'Codex', id, file, timestamp: row.timestamp, cwd, model: p.model, projects }); const c = gitProject(projects, cwd); if (c && (!best || c.canonicalPath.length > best.canonicalPath.length)) best = c; addTokens(event.tokens, normalizeUsage(row)); if (/tool|function_call|command_execution/.test(row.type || '') || p.type === 'function_call') event.tools++; if (/compact|summary/i.test(row.type || '') || /compact/i.test(p.event_type || '')) event.compactions++; if (row.timestamp && (!event.timestamp || row.timestamp > event.timestamp)) event.timestamp = iso(row.timestamp); }); if (event) { if (best) { event.projectId = best.id; event.projectPath = best.canonicalPath; event.attributionConfidence = CONFIDENCE.confirmed; } sessions.set(event.id, event); } } return { sessions: [...sessions.values()], diagnostics: { codexFilesInspected: inspected, codexFilesChanged: changed, codexRecordsParsed: parsed } }; }
export function scanCursor(projects, root = path.join(home, '.cursor', 'projects'), previous = new Map()) { const sessions = []; let inspected = 0, changed = 0; let dirs = []; try { dirs = fs.readdirSync(root, { withFileTypes: true }).filter((x) => x.isDirectory()); } catch {} for (const d of dirs) { const candidate = projects.find((p) => d.name.includes(p.canonicalPath.replace(/^\//, '').replaceAll('/', '-'))); for (const file of walk(path.join(root, d.name, 'agent-transcripts'), { maxDepth: 3, accept: (f) => /\.(jsonl|json)$/.test(f) })) { inspected++; const prior = previous.get(file); if (prior?.sourceFingerprint === fingerprint(file)) { sessions.push(prior); continue; } changed++; const s = stat(file); sessions.push(makeSession({ agent: 'Cursor', id: hash(file), file, timestamp: s?.mtime.toISOString(), cwd: candidate?.canonicalPath, projects, confidence: candidate ? CONFIDENCE.strong : CONFIDENCE.weak })); } } return { sessions, diagnostics: { cursorFilesInspected: inspected, cursorFilesChanged: changed, cursorRecordsParsed: 0 } }; }

function capabilityType(file) { const b = path.basename(file); if (b === 'SKILL.md') return 'Agent Skill'; if (file.includes('/.claude/commands/')) return 'Command'; if (b === 'CLAUDE.md' || b === 'AGENTS.md' || b === '.cursorrules' || file.includes('/.cursor/rules/')) return 'Instruction'; return 'Capability'; }
function safeCapabilityMetadata(file) { let text = ''; try { text = fs.readFileSync(file, 'utf8').slice(0, 5000); } catch {} const front = text.match(/^---\n([\s\S]*?)\n---/); const name = front?.[1].match(/^name:\s*["']?([^\n"']+)/m)?.[1]?.trim(); const description = front?.[1].match(/^description:\s*["']?([^\n"']+)/m)?.[1]?.trim(); const heading = text.match(/^#\s+(.+)$/m)?.[1]?.trim(); return { name: name || heading || (path.basename(file) === 'SKILL.md' ? path.basename(path.dirname(file)) : path.basename(file, path.extname(file))), description: description || null, summaryKind: description ? 'source metadata' : 'unavailable' }; }
export function discoverCapabilities(projects, sources) { const roots = [{ root:path.join(home,'.claude','skills'),origin:'Claude user',depth:5},{root:path.join(home,'.claude','plugins'),origin:'Claude plugin',depth:6},{root:path.join(home,'.claude','scheduled-tasks'),origin:'Claude user',depth:4},{root:path.join(home,'.codex','skills'),origin:'Codex user',depth:5},{root:path.join(home,'.codex','plugins'),origin:'Codex plugin',depth:5},{root:path.join(home,'.cursor','skills-cursor'),origin:'Cursor user',depth:4},{root:path.join(home,'.cursor','agents'),origin:'Cursor user',depth:4},{root:path.join(home,'.cursor','plugins'),origin:'Cursor plugin',depth:5},{root:sources.projectsRoot,origin:'Project',depth:6}]; const found = new Map(); for (const r of roots) for (const file of walk(r.root,{maxDepth:r.depth,accept:(f)=>['SKILL.md','CLAUDE.md','AGENTS.md','.cursorrules'].includes(path.basename(f)) || /\/\.cursor\/rules\/.*\.mdc$/.test(f) || /\/\.claude\/commands\/[^/]+\.md$/.test(f)})) found.set(file,r.origin); return [...found].map(([location,origin])=>{const s=stat(location),meta=safeCapabilityMetadata(location),p=projects.find(x=>within(location,x.canonicalPath));const key=path.basename(location)==='SKILL.md'?path.basename(path.dirname(location)):path.basename(location,path.extname(location));return {id:`capability:${hash(location)}`,name:meta.name,type:capabilityType(location),location,origin,projectId:p?.id||null,sourceHash:hash(`${s?.size}:${s?.mtimeMs}`),lastModified:s?.mtime.toISOString()||null,capabilityKey:key.toLowerCase(),description:meta.description,summaryKind:meta.summaryKind,isPrivate:location.includes('(private)'),usageCount:0,usageConfidence:CONFIDENCE.unknown,health:'Never Observed',statusNote:'Installed/configured; no safe usage evidence yet.'};}); }
function mapCapabilitySkill(skill, capabilities) { const key = skill.toLowerCase().split(':').at(-1); return capabilities.find((c) => c.capabilityKey === skill.toLowerCase() || c.capabilityKey === key || c.name.toLowerCase() === skill.toLowerCase() || c.name.toLowerCase().endsWith(`:${key}`)) || null; }
export function capabilityUsageEvents(signals, capabilities, sessions) { const bySession = new Map(sessions.map((s) => [s.id, s])); const events = new Map(); for (const signal of signals) { const cap = mapCapabilitySkill(signal.skill, capabilities), s = bySession.get(signal.sessionId); if (!cap || !s) continue; const id = `${cap.id}:${s.id}`; if (!events.has(id)) events.set(id,{id,timestamp:signal.timestamp||s.timestamp,capabilityId:cap.id,agent:'Claude',projectId:s.projectId||null,evidenceType:'Claude structured attributionSkill',confidence:CONFIDENCE.confirmed,contextLabel:`${signal.skill} workflow`,sourceReference:signal.sourceFile}); } return [...events.values()]; }
export function gitMetrics(project) { const p=project.canonicalPath, n=(a)=>Number(git(p,a)||0), changes=(git(p,['log','--numstat','--format='])||'').split('\n').filter(Boolean).reduce((x,l)=>{const[a,d]=l.split('\t');x.additions+=Number(a)||0;x.deletions+=Number(d)||0;return x;},{additions:0,deletions:0}); const files=walk(p,{maxDepth:5,maxFiles:1500,ignore:['dist','build','.next','vendor','coverage'],accept:(f)=>{const s=stat(f);return(s?.size||0)<1e6&&/\.(js|mjs|cjs|ts|tsx|jsx|py|go|rs|html|css|md|json|yml|yaml|sql|sh)$/i.test(f)}});let lines=0;for(const f of files)try{lines+=fs.readFileSync(f,'utf8').split('\n').length}catch{} return {commits:n(['rev-list','--count','HEAD']),...changes,netChange:changes.additions-changes.deletions,filesMeasured:files.length,linesMeasured:lines}; }
const headline = (s) => [CONFIDENCE.confirmed, CONFIDENCE.strong].includes(s.attributionConfidence);
function efficiency(sessions, now = new Date()) { const end = new Date(now), start = new Date(end); start.setDate(start.getDate()-30); const previousStart = new Date(start); previousStart.setDate(previousStart.getDate()-30); const select=(from,to)=>sessions.filter(s=>headline(s)&&s.timestamp&&new Date(s.timestamp)>=from&&new Date(s.timestamp)<to); const current=select(start,end), previous=select(previousStart,start); const calc=(set)=>{const eligible=set.filter(s=>tokenActivity(s.tokens)>0);const tokens=eligible.reduce((a,s)=>a+tokenActivity(s.tokens),0);const cache=eligible.reduce((a,s)=>a+(s.tokens.cacheRead||0),0);const tools=set.reduce((a,s)=>a+s.tools,0);return {sessions:set.length,tokenSessions:eligible.length,tokensPerSession:eligible.length?tokens/eligible.length:null,toolsPerSession:set.length?tools/set.length:null,cacheReadRatio:tokens?cache/tokens:null,activeDays:new Set(set.map(s=>s.timestamp?.slice(0,10))).size};}; const c=calc(current),p=calc(previous); const comparison=(name)=>c.tokenSessions>=3&&p.tokenSessions>=3&&c[name]!=null&&p[name]!=null?{value:c[name],previous:p[name],change:(c[name]-p[name])/Math.abs(p[name]||1),comparable:true}:{value:c[name],comparable:false}; return {period:{from:start.toISOString(),to:end.toISOString()},current:c,previous:p,components:{tokensPerSession:comparison('tokensPerSession'),cacheReadRatio:comparison('cacheReadRatio'),toolsPerSession:c.sessions>=3&&p.sessions>=3?{value:c.toolsPerSession,previous:p.toolsPerSession,change:(c.toolsPerSession-p.toolsPerSession)/Math.abs(p.toolsPerSession||1),comparable:true}:{value:c.toolsPerSession,comparable:false}}}; }
export function derive(index) { const byProject=new Map(index.projects.map(p=>[p.id,{...p,sessions:[]}])); for(const s of index.sessions)if(s.projectId&&byProject.has(s.projectId)&&headline(s))byProject.get(s.projectId).sessions.push(s); const capEvents=index.capabilityUsageEvents||[]; const caps=index.capabilities.map(c=>{const es=capEvents.filter(e=>e.capabilityId===c.id&&[CONFIDENCE.confirmed,CONFIDENCE.strong].includes(e.confidence));return {...c,usageCount:es.length,usageConfidence:es.length?CONFIDENCE.confirmed:CONFIDENCE.unknown,health:es.length?'Active':'Never Observed',recentUsage:es.sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,5)};}); const projects=[...byProject.values()].map(p=>{const tokens=p.sessions.reduce((a,s)=>{addTokens(a,s.tokens);return a;},emptyTokens());return {...p,metrics:gitMetrics(p),sessionCount:p.sessions.length,agents:[...new Set(p.sessions.map(s=>s.agent))],tokens,recentActivity:p.sessions.map(s=>s.timestamp).filter(Boolean).sort().at(-1)||p.git.lastCommitAt};}); const total=index.sessions.reduce((a,s)=>{a.sessions++;addTokens(a.tokens,s.tokens);a.tools+=s.tools;a.compactions+=s.compactions;return a;},{sessions:0,tools:0,compactions:0,tokens:emptyTokens()}); const diagnostics=index.diagnostics||{};return {...index,projects,capabilities:caps,capabilityUsageEvents:capEvents,efficiency:efficiency(index.sessions),summary:{...total,activeProjects:projects.filter(p=>p.sessionCount||p.git.lastCommitAt).length,totalObservedTokenActivity:tokenActivity(total.tokens),agents:[...new Set(index.sessions.map(s=>s.agent))],capabilityUses:capEvents.length,lastScanAt:new Date().toISOString(),diagnostics}}; }
export function scan(sources, previous=null) { const began=Date.now(),projects=discoverProjects(sources.projectsRoot),prior=new Map((previous?.sessions||[]).filter(s=>s.sourceFile).map(s=>[s.sourceFile,s.tokens?s:{...s,tokens:{freshInput:s.usage?.input||0,output:s.usage?.output||0,cacheRead:s.usage?.cached||0,cacheCreation:0,reasoning:s.usage?.reasoning||0,other:0}}]));const claude=scanClaude(projects,sources.claudeRoot,prior),codex=scanCodex(projects,sources.codexRoot,prior),cursor=scanCursor(projects,sources.cursorRoot,prior);const sessions=[...claude.sessions,...codex.sessions,...cursor.sessions],capabilities=discoverCapabilities(projects,sources),events=capabilityUsageEvents(claude.skillSignals,capabilities,sessions);return derive({schemaVersion:2,metricVersion:METRIC_VERSION,sources,projects,sessions,capabilities,capabilityUsageEvents:events,errors:[],diagnostics:{...claude.diagnostics,...codex.diagnostics,...cursor.diagnostics,durationMs:Date.now()-began}}); }
export function defaultSources(){return {projectsRoot:path.join(home,'Dropbox','Projects'),claudeRoot:path.join(home,'.claude','projects'),codexRoot:path.join(home,'.codex','sessions'),cursorRoot:path.join(home,'.cursor','projects')}};
