import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';

export const CONFIDENCE = { confirmed: 'Confirmed', strong: 'Strongly inferred', weak: 'Weakly inferred', unknown: 'Unknown' };
export const METRIC_VERSION = '2.0';
const home = process.env.HOME;
const hash = (v) => crypto.createHash('sha256').update(String(v)).digest('hex').slice(0, 16);
const stat = (p) => { try { return fs.statSync(p); } catch { return null; } };
const fingerprint = (p) => { const s = stat(p); return s ? `${s.size}:${Math.round(s.mtimeMs)}` : null; };
const iso = (v) => { const d = new Date(v); return Number.isNaN(d.getTime()) ? null : d.toISOString(); };
const normal = (p) => path.resolve(p).replace(/\\/g, '/');
const within = (child, parent) => normal(child).startsWith(`${normal(parent)}/`) || normal(child) === normal(parent);
const git = (cwd, args) => { try { return execFileSync('git', args, { cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(); } catch { return null; } };
function walk(root, { maxDepth = 7, maxFiles = Infinity, accept = () => true, ignore = [] } = {}) { const out = []; const ignored = new Set(['.git', 'node_modules', '.dashboard-data', 'archive', 'Archives', ...ignore]); function visit(dir, depth) { if (depth > maxDepth || out.length >= maxFiles) return; let es; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; } for (const e of es) { if (out.length >= maxFiles) return; const p = path.join(dir, e.name); if (e.isDirectory()) { if (!ignored.has(e.name)) visit(p, depth + 1); } else if (accept(p, e)) out.push(p); } } visit(root, 0); return out; }
// Bounded metadata parsing: inspect the newest appended JSONL records without retaining transcripts.
function readJsonlBounded(file, onRow) { try { const size=stat(file)?.size||0,chunk=512*1024,ranges=size<=chunk?[{start:0,length:size}]:[{start:0,length:chunk},{start:size-chunk,length:chunk}],fd=fs.openSync(file,'r');for(const {start,length} of ranges){const buffer=Buffer.alloc(length);fs.readSync(fd,buffer,0,length,start);let text=buffer.toString('utf8');if(start>0)text=text.slice(text.indexOf('\n')+1);for(const line of text.split('\n'))if(line.trim())try{onRow(JSON.parse(line));}catch{}}fs.closeSync(fd);}catch{} }
function gitProject(projects, cwd) { if (!cwd) return null; return projects.filter((p) => within(cwd, p.canonicalPath)).sort((a, b) => b.canonicalPath.length - a.canonicalPath.length)[0] || null; }
const emptyTokens = () => ({ freshInput: 0, output: 0, cacheRead: 0, cacheCreation: 0, reasoning: 0, other: 0 });
export function normalizeUsage(source = {}) { const u = source.usage || source.message?.usage || source.payload?.usage || {}; const n = (v) => Number.isFinite(Number(v)) ? Number(v) : 0; return { freshInput: n(u.input_tokens ?? u.inputTokens), output: n(u.output_tokens ?? u.outputTokens), cacheRead: n(u.cache_read_input_tokens ?? u.cacheReadInputTokens ?? u.cached_tokens), cacheCreation: n(u.cache_creation_input_tokens ?? u.cacheCreationInputTokens), reasoning: n(u.reasoning_tokens ?? u.reasoningTokens), other: n(u.other_tokens ?? u.otherTokens) }; }
export const tokenActivity = (t = emptyTokens()) => Object.values(t).reduce((a, n) => a + (Number(n) || 0), 0);
function addTokens(a, b = emptyTokens()) { for (const k of Object.keys(a)) a[k] += b[k] || 0; }
function encodedPath(p) { return normal(p).replace(/[^A-Za-z0-9]/g, '-'); }
function projectFromClaudeFolder(file, projects, root) { const top = path.relative(root, file).split(path.sep)[0]; return projects.find((p) => encodedPath(p.canonicalPath) === top) || null; }
function makeSession({ agent, host, id, file, timestamp, cwd, model, projects, confidence = CONFIDENCE.confirmed }) { const p = gitProject(projects, cwd); return { id: `${agent}:${id}`, agent, host: host || agent, sourceFile: file, sourceFingerprint: fingerprint(file), timestamp: iso(timestamp), projectId: p?.id || null, projectPath: p?.canonicalPath || null, attributionConfidence: p ? confidence : CONFIDENCE.unknown, model: model || null, tokens: emptyTokens(), tools: 0, compactions: 0, attributedSkills: [] }; }

export function discoverProjects(root) { const roots = new Set(); function visit(dir, depth = 0) { if (depth > 5) return; let es; try { es = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; } if (es.some((e) => e.name === '.git')) roots.add(dir); for (const e of es) if (e.isDirectory() && !['.git', 'node_modules', '.dashboard-data', 'Archives', 'archive'].includes(e.name)) visit(path.join(dir, e.name), depth + 1); } visit(root); return [...roots].sort().map((canonicalPath) => ({ id: `project:${hash(canonicalPath)}`, name: path.basename(canonicalPath), canonicalPath, git: { isRepository: true, branch: git(canonicalPath, ['branch', '--show-current']) || null, remote: git(canonicalPath, ['remote', 'get-url', 'origin']) || null, lastCommitAt: iso(git(canonicalPath, ['log', '-1', '--format=%cI'])) }, confidence: CONFIDENCE.confirmed })); }

export function scanClaude(projects, root = path.join(home, '.claude', 'projects'), previous = new Map()) { const sessions = new Map(); const skillSignals = []; let parsed = 0, inspected = 0, changed = 0; for (const file of walk(root, { maxDepth: 4, accept: (f) => f.endsWith('.jsonl') })) { inspected++; const prior = previous.get(file); if (prior?.sourceFingerprint === fingerprint(file)) { sessions.set(prior.id, prior); continue; } changed++; let event, best; readJsonlBounded(file, (row) => { parsed++; const id = row.sessionId || path.basename(file, '.jsonl'); if (!event) event = makeSession({ agent: 'Claude', host:'Claude Code', id, file, timestamp: row.timestamp, cwd: row.cwd, model: row.message?.model, projects }); const candidate = gitProject(projects, row.cwd); if (candidate && (!best || candidate.canonicalPath.length > best.canonicalPath.length)) best = candidate; addTokens(event.tokens, normalizeUsage(row)); if (row.type === 'assistant' && Array.isArray(row.message?.content)) event.tools += row.message.content.filter((x) => x.type === 'tool_use').length; if (row.isCompactSummary || row.compactMetadata || /compact|summary/i.test(row.type || '')) event.compactions++; if (row.timestamp && (!event.timestamp || row.timestamp > event.timestamp)) event.timestamp = iso(row.timestamp); if (row.attributionSkill) { const skill=String(row.attributionSkill); skillSignals.push({ sessionId: event.id, skill, timestamp: iso(row.timestamp), cwd: row.cwd, sourceFile: file }); if(!event.attributedSkills.some(x=>x.skill===skill))event.attributedSkills.push({skill,timestamp:iso(row.timestamp)}); } }); if (event) { const slugProject = projectFromClaudeFolder(file, projects, root); const selected = best || slugProject; if (selected) { event.projectId = selected.id; event.projectPath = selected.canonicalPath; event.attributionConfidence = best ? CONFIDENCE.confirmed : CONFIDENCE.strong; } sessions.set(event.id, event); } } return { sessions: [...sessions.values()], skillSignals, diagnostics: { claudeFilesInspected: inspected, claudeFilesChanged: changed, claudeRecordsParsed: parsed } }; }
export function scanCodex(projects, root = path.join(home, '.codex', 'sessions'), previous = new Map()) { const sessions = new Map(); let parsed = 0, inspected = 0, changed = 0; for (const file of walk(root, { maxDepth: 5, accept: (f) => f.endsWith('.jsonl') })) { inspected++; const prior = previous.get(file); if (prior?.sourceFingerprint === fingerprint(file)) { sessions.set(prior.id, prior); continue; } changed++; let event, best; readJsonlBounded(file, (row) => { parsed++; const p = row.payload || {}; const id = p.id || p.session_id || p.sessionId || path.basename(file, '.jsonl'); const cwd = p.cwd || p.working_directory || p.workspace?.cwd; if (!event) event = makeSession({ agent: 'Codex', host:'Codex CLI', id, file, timestamp: row.timestamp, cwd, model: p.model, projects }); const c = gitProject(projects, cwd); if (c && (!best || c.canonicalPath.length > best.canonicalPath.length)) best = c; addTokens(event.tokens, normalizeUsage(row)); if (/tool|function_call|command_execution/.test(row.type || '') || p.type === 'function_call') event.tools++; if (/compact|summary/i.test(row.type || '') || /compact/i.test(p.event_type || '')) event.compactions++; if (row.timestamp && (!event.timestamp || row.timestamp > event.timestamp)) event.timestamp = iso(row.timestamp); }); if (event) { if (best) { event.projectId = best.id; event.projectPath = best.canonicalPath; event.attributionConfidence = CONFIDENCE.confirmed; } sessions.set(event.id, event); } } return { sessions: [...sessions.values()], diagnostics: { codexFilesInspected: inspected, codexFilesChanged: changed, codexRecordsParsed: parsed } }; }
export function scanCursor(projects, root = path.join(home, '.cursor', 'projects'), previous = new Map()) { const sessions = []; let inspected = 0, changed = 0; let dirs = []; try { dirs = fs.readdirSync(root, { withFileTypes: true }).filter((x) => x.isDirectory()); } catch {} for (const d of dirs) { const candidate = projects.find((p) => d.name.includes(p.canonicalPath.replace(/^\//, '').replaceAll('/', '-'))); for (const file of walk(path.join(root, d.name, 'agent-transcripts'), { maxDepth: 3, accept: (f) => /\.(jsonl|json)$/.test(f) })) { inspected++; const prior = previous.get(file); if (prior?.sourceFingerprint === fingerprint(file)) { sessions.push(prior); continue; } changed++; const s = stat(file); sessions.push(makeSession({ agent: 'Cursor', host:'Cursor', id: hash(file), file, timestamp: s?.mtime.toISOString(), cwd: candidate?.canonicalPath, projects, confidence: candidate ? CONFIDENCE.strong : CONFIDENCE.weak })); } } return { sessions, diagnostics: { cursorFilesInspected: inspected, cursorFilesChanged: changed, cursorRecordsParsed: 0 } }; }
export function discoverVsCodeAI(homeDir = home) { const extensionsRoot=path.join(homeDir,'.vscode','extensions'); let entries=[]; try { entries=fs.readdirSync(extensionsRoot,{withFileTypes:true}).filter(e=>e.isDirectory()).map(e=>e.name); } catch {} const known=entries.filter(x=>/copilot|claude-code|openai\.chatgpt|continue/i.test(x)).map(name=>({name,installed:true})); const storage=path.join(homeDir,'Library','Application Support','Code','User','globalStorage'); return {host:'VS Code',detected:stat(extensionsRoot)!==null,aiExtensions:known,history:'No reliable AI-session transcript format was found in the safe local inspection; VS Code extension storage is not counted as AI activity.' ,storagePresent:stat(storage)!==null}; }
export function discoverNativeAutomations(homeDir=home) { const settings=path.join(homeDir,'.claude','settings.json');let value;try{value=JSON.parse(fs.readFileSync(settings,'utf8'));}catch{return [];}if(value.autoCompactEnabled!==true||!Number.isFinite(Number(value.autoCompactWindow)))return [];const window=Number(value.autoCompactWindow);return [{id:`capability:${hash(`${settings}:auto-compact`)}`,name:'Claude Auto-Compact',type:'Automation',location:settings,origin:'Claude native configuration',projectId:null,sourceHash:hash(`${value.autoCompactEnabled}:${window}`),lastModified:stat(settings)?.mtime.toISOString()||null,capabilityKey:'claude-auto-compact',description:`Automatically compacts context at ${new Intl.NumberFormat('en-US').format(window)} tokens.`,summaryKind:'native configuration',isPrivate:false,usageCount:0,usageConfidence:CONFIDENCE.unknown,health:'Active',statusNote:'Enabled through native Claude Code configuration.',active:true,scope:'User / Global',agent:'Claude Code',trigger:`Context reaches ${new Intl.NumberFormat('en-US').format(window)} tokens`,behavior:`Automatically compacts context at ${new Intl.NumberFormat('en-US').format(window)} tokens.`,implementation:'Native Claude Code configuration',portability:'Claude-specific',compatibleAgents:['Claude'],setupRecipe:'Verify the installed Claude Code version supports autoCompactEnabled and autoCompactWindow before proposing these native settings; preserve existing configuration and apply only with user approval.'}]; }

function capabilityType(file) { const b = path.basename(file); if (b === 'SKILL.md') return 'Agent Skill'; if (file.includes('/.claude/commands/')) return 'Command'; if (b === 'CLAUDE.md' || b === 'AGENTS.md' || b === '.cursorrules' || file.includes('/.cursor/rules/')) return 'Instruction'; return 'Capability'; }
function safeCapabilityMetadata(file) { let text = ''; try { text = fs.readFileSync(file, 'utf8').slice(0, 5000); } catch {} const front = text.match(/^---\n([\s\S]*?)\n---/); const name = front?.[1].match(/^name:\s*["']?([^\n"']+)/m)?.[1]?.trim(); const description = front?.[1].match(/^description:\s*["']?([^\n"']+)/m)?.[1]?.trim(); const heading = text.match(/^#\s+(.+)$/m)?.[1]?.trim(); return { name: name || heading || (path.basename(file) === 'SKILL.md' ? path.basename(path.dirname(file)) : path.basename(file, path.extname(file))), description: description || null, summaryKind: description ? 'source metadata' : 'unavailable' }; }
export function discoverCapabilities(projects, sources) { const roots = [{ root:path.join(home,'.claude','skills'),origin:'Claude user',depth:5},{root:path.join(home,'.claude','plugins'),origin:'Claude plugin',depth:6},{root:path.join(home,'.claude','scheduled-tasks'),origin:'Claude user',depth:4},{root:path.join(home,'.codex','skills'),origin:'Codex user',depth:5},{root:path.join(home,'.codex','plugins'),origin:'Codex plugin',depth:5},{root:path.join(home,'.cursor','skills-cursor'),origin:'Cursor user',depth:4},{root:path.join(home,'.cursor','agents'),origin:'Cursor user',depth:4},{root:path.join(home,'.cursor','plugins'),origin:'Cursor plugin',depth:5},{root:sources.projectsRoot,origin:'Project',depth:6}]; const found = new Map(); for (const r of roots) for (const file of walk(r.root,{maxDepth:r.depth,accept:(f)=>['SKILL.md','CLAUDE.md','AGENTS.md','.cursorrules'].includes(path.basename(f)) || /\/\.cursor\/rules\/.*\.mdc$/.test(f) || /\/\.claude\/commands\/[^/]+\.md$/.test(f)})) found.set(file,r.origin); return [...found].map(([location,origin])=>{const s=stat(location),meta=safeCapabilityMetadata(location),p=projects.find(x=>within(location,x.canonicalPath));const key=path.basename(location)==='SKILL.md'?path.basename(path.dirname(location)):path.basename(location,path.extname(location));return {id:`capability:${hash(location)}`,name:meta.name,type:capabilityType(location),location,origin,projectId:p?.id||null,sourceHash:hash(`${s?.size}:${s?.mtimeMs}`),lastModified:s?.mtime.toISOString()||null,capabilityKey:key.toLowerCase(),description:meta.description,summaryKind:meta.summaryKind,isPrivate:location.includes('(private)'),usageCount:0,usageConfidence:CONFIDENCE.unknown,health:'Never Observed',statusNote:'Installed/configured; no safe usage evidence yet.'};}); }
function mapCapabilitySkill(skill, capabilities) { const key = skill.toLowerCase().split(':').at(-1); return capabilities.find((c) => c.capabilityKey === skill.toLowerCase() || c.capabilityKey === key || c.name.toLowerCase() === skill.toLowerCase() || c.name.toLowerCase().endsWith(`:${key}`)) || null; }
export function capabilityUsageEvents(signals, capabilities, sessions) { const bySession = new Map(sessions.map((s) => [s.id, s])); const events = new Map(); for (const signal of signals) { const cap = mapCapabilitySkill(signal.skill, capabilities), s = bySession.get(signal.sessionId); if (!cap || !s) continue; const id = `${cap.id}:${s.id}`; if (!events.has(id)) events.set(id,{id,timestamp:signal.timestamp||s.timestamp,capabilityId:cap.id,agent:'Claude',projectId:s.projectId||null,evidenceType:'Claude structured attributionSkill',confidence:CONFIDENCE.confirmed,contextLabel:`${signal.skill} workflow`,sourceReference:signal.sourceFile}); } return [...events.values()]; }
function titleCase(value) { return String(value).replace(/[-_]+/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase()); }
export function capabilityGroupKey(capability) { const p = capability.location.replace(/\\/g,'/'); const plugin = p.match(/\/plugins\/(?:cache|marketplaces)\/([^/]+)/); if (plugin) return `plugin:${plugin[1].toLowerCase()}`; const skill = p.match(/\/skills(?:-[^/]+)?\/([^/]+)/); if (skill) return `skill:${skill[1].toLowerCase()}`; const command = p.match(/\/\.claude\/commands\/([^/]+)/); if (command) return `command:${command[1].replace(/\.md$/,'').toLowerCase()}`; return `reference:${capability.id}`; }
function componentName(capability) { const p=capability.location.replace(/\\/g,'/'); const command=p.match(/\/\.claude\/commands\/([^/]+)\.md$/)?.[1]; if(command)return titleCase(command); const file=path.basename(p); return file==='SKILL.md' ? 'Main skill' : file.replace(/\.[^.]+$/,''); }
export const PROJECT_STATUSES=['Active','Paused','Waiting','Done','Archived'];
const INTEGRATION_NAMES=/discord|telegram|imessage|slack|mcp|notify|hook/i;
export function classifyCapability(capability) { const location=(capability.location||'').replace(/\\/g,'/'); const groupKey=capability.groupKey||capabilityGroupKey(capability); const rawType=capability.type||''; const type=rawType==='Automation'?'Automation':rawType==='Instruction'?'Instructions':groupKey.startsWith('plugin:')?(INTEGRATION_NAMES.test(capability.name||groupKey)?'Integrations':'Tools'):rawType==='Agent Skill'||rawType==='Command'||groupKey.startsWith('skill:')?'Skills':'Tools'; const scope=capability.scope||(capability.projectId||location.includes('/Dropbox/Projects/')?'Project-specific':location.includes('/scheduled-tasks/')?'Custom':'Shared'); return {type,scope}; }
function artifactState(group) { const components=group.components||[]; if(group.type==='Automation')return components.some(c=>c.active)?'Complete':'Unknown';if(group.groupKey.startsWith('skill:')) return components.some(c=>path.basename(c.location)==='SKILL.md')?'Complete':'Broken'; if(group.type==='Instruction'||group.groupKey.startsWith('command:')) return components.length?'Complete':'Broken'; return 'Unknown'; }
function installationComponents(group) { const byType={}; for(const c of group.components) byType[c.type]=(byType[c.type]||0)+1; return Object.entries(byType).map(([name,count])=>({name,count,expected:null,state:'Observed'})); }
function knownCompatibility(group) { const compatible=new Set(); for(const c of group.components) { for(const agent of c.compatibleAgents||[])compatible.add(agent);const location=c.location.replace(/\\/g,'/'); if(c.origin.startsWith('Claude')||location.includes('/.claude/')) compatible.add('Claude'); if(c.origin.startsWith('Codex')||location.includes('/.codex/')) compatible.add('Codex'); if(c.origin.startsWith('Cursor')||location.includes('/.cursor/')) compatible.add('Cursor'); } return [...compatible]; }
function coverage(installed, compatible) { return ['Claude','Codex','Cursor'].map(agent=>({agent,state:installed.includes(agent)?'Installed':compatible.includes(agent)?'Not installed':'Compatibility unknown'})); }
export function groupCapabilities(rawCapabilities, usageEvents) { const groups = new Map(); for (const c of rawCapabilities) { const groupKey=capabilityGroupKey(c); if(!groups.has(groupKey)) groups.set(groupKey,{id:`capability-group:${hash(groupKey)}`,groupKey,name:groupKey.startsWith('plugin:')||groupKey.startsWith('skill:')?titleCase(groupKey.split(':')[1]):c.name,type:groupKey.startsWith('plugin:')?'Plugin':c.type,origin:c.origin,description:c.description,summaryKind:c.summaryKind,isPrivate:c.isPrivate,scope:c.scope,active:c.active,agent:c.agent,trigger:c.trigger,behavior:c.behavior,implementation:c.implementation,portability:c.portability,setupRecipe:c.setupRecipe,components:[],installation:[],agents:new Set(),usedByAgents:new Set()}); const g=groups.get(groupKey); const es=usageEvents.filter(e=>e.capabilityId===c.id); g.components.push({...c,componentName:componentName(c),usageCount:es.length,recentUsage:es}); g.installation.push(c.location); const location=c.location.replace(/\\/g,'/'); if(c.origin.startsWith('Claude')||location.includes('/.claude/'))g.agents.add('Claude'); if(c.origin.startsWith('Codex')||location.includes('/.codex/'))g.agents.add('Codex'); if(c.origin.startsWith('Cursor')||location.includes('/.cursor/'))g.agents.add('Cursor'); for(const e of es)g.usedByAgents.add(e.agent); if(!g.description&&c.description){g.description=c.description;g.summaryKind=c.summaryKind;} }
  return [...groups.values()].map(g=>{const uses=g.components.reduce((n,c)=>n+c.usageCount,0),latest=g.components.flatMap(c=>c.recentUsage).sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,8),installedOn=[...g.agents],compatibleAgents=knownCompatibility(g),classification=classifyCapability({...g,projectId:g.components.find(c=>c.projectId)?.projectId,location:g.installation[0]}); const modified=g.components.map(c=>c.lastModified).filter(Boolean).sort().at(-1); const history=[...(modified?[{timestamp:modified,type:'Modified',confidence:'Observed',label:'Local capability configuration modified'}]:[]),...latest.map(x=>({timestamp:x.timestamp,type:'Used',confidence:x.confidence,label:`Used by ${x.agent}`}))].sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))); const active=g.active||uses>0;return {...g,...classification,agents:installedOn,installedOn,compatibleAgents,agentCoverage:coverage(installedOn,compatibleAgents),artifactState:artifactState(g),installationComponents:installationComponents(g),usedByAgents:[...g.usedByAgents],usageCount:uses,lastUsedAt:latest[0]?.timestamp||null,recentUsage:latest,history,health:active?'Active':'No observed use',statusNote:g.active?'Enabled through native agent configuration.':uses?'Structured activity has been observed.':'No confirmed use has been found in the available local history.',ownership:{ownedArtifacts:g.installation,management:'Inventory only — no change action is automatic.'},updateStatus:'Update status unknown'};}); }
export function maintenanceGroups(capabilities) { const groups={needsAction:[],updates:[],usageReview:[],coverage:[]}; for(const c of capabilities){const reasons=[]; if(['Broken','Partial'].includes(c.artifactState)) reasons.push({group:'needsAction',label:`Installation ${c.artifactState.toLowerCase()}`,impact:'Some known capability artifacts may be unavailable.',next:'View installation before making any change.'}); if(c.updateStatus==='Update available') reasons.push({group:'updates',label:'Update available',impact:'A newer known upstream version exists.',next:'Review the update source and changes first.'}); if(c.health!=='Active') reasons.push({group:'usageReview',label:'No observed use',impact:'This may be intentionally specialised; nothing is necessarily broken.',next:'Keep it, or review the capability when convenient.'}); if(c.agentCoverage.some(x=>x.state==='Not installed')) reasons.push({group:'coverage',label:'Available for another agent',impact:'Nothing is broken; another supported installation is absent.',next:'Review installation coverage before planning a safe install.'}); for(const reason of reasons)groups[reason.group].push({...c,reason});} return groups; }
export const ACHIEVEMENT_TIERS=Object.freeze([
  {id:'bronze',label:'Bronze',min:1,slot:'assets/badges/bronze.svg'},
  {id:'silver',label:'Silver',min:2,slot:'assets/badges/silver.svg'},
  {id:'gold',label:'Gold',min:3,slot:'assets/badges/gold.svg'},
  {id:'platinum',label:'Platinum',min:4,slot:'assets/badges/platinum.svg'},
  {id:'diamond',label:'Diamond',min:5,slot:'assets/badges/diamond.svg'},
  {id:'mythic',label:'Mythic',min:6,slot:'assets/badges/mythic.svg'}
]);
const achievementTier=(stage=1)=>ACHIEVEMENT_TIERS[Math.max(0,Math.min(ACHIEVEMENT_TIERS.length-1,stage-1))];
const achievement=(base,stage)=>({...base,tier:achievementTier(stage),badge:{kind:'fallback-vector',assetSlot:achievementTier(stage).slot}});
export function achievementsFor(index) { const sessions=index.sessions||[], latest=sessions.map(s=>s.timestamp).filter(Boolean).sort().at(-1)||null, activeDays=new Set(sessions.map(s=>s.timestamp?.slice(0,10)).filter(Boolean)).size, agents=new Set(sessions.map(s=>s.agent)).size, capabilityUses=Number(index.summary?.capabilityUses||0), trend=index.efficiency?.components?.tokensPerSession, out=[]; if(agents>=2)out.push(achievement({id:'multi-agent-builder',name:'Multi-Agent Builder',description:'Observed work across more than one AI agent.',rule:'At least two observed agents',evidence:`${agents} agents`,earnedAt:latest,period:'all observed history'},agents>=3?3:1)); if(capabilityUses>=3)out.push(achievement({id:'capability-in-practice',name:'Capability in Practice',description:'Confirmed structured use of installed capabilities.',rule:'At least three confirmed capability-use events',evidence:`${capabilityUses} confirmed uses`,earnedAt:latest,period:'all observed history'},capabilityUses>=60?6:capabilityUses>=30?5:capabilityUses>=15?4:capabilityUses>=6?3:2)); if(activeDays>=7)out.push(achievement({id:'consistent-builder',name:'Consistent Builder',description:'Observed AI development activity on several different days.',rule:'At least seven active days',evidence:`${activeDays} active days`,earnedAt:latest,period:'all observed history'},activeDays>=60?6:activeDays>=30?5:activeDays>=14?4:3)); if(trend?.comparable&&trend.change<=-.05)out.push(achievement({id:'leaner-loop',name:'Leaner Loop',description:'Observed token activity per session improved against a comparable personal period.',rule:'At least 5% lower observed token activity per session',evidence:`${Math.round(Math.abs(trend.change)*100)}% lower`,earnedAt:latest,period:'comparable 30-day periods'},trend.change<=-.35?6:trend.change<=-.25?5:trend.change<=-.18?4:trend.change<=-.1?3:2)); return out; }
export function applyProjectMetadata(index, metadata={}) { const records=metadata.projects||{}; const projects=index.projects.map(p=>{const m=records[p.id]||{}; return {...p,pinned:Boolean(m.pinned),status:PROJECT_STATUSES.includes(m.status)?m.status:null,note:typeof m.note==='string'?m.note.slice(0,500):''};}); return {...index,projects}; }
export function gitMetrics(project) { const p=project.canonicalPath, n=(a)=>Number(git(p,a)||0), changes=(git(p,['log','--numstat','--format='])||'').split('\n').filter(Boolean).reduce((x,l)=>{const[a,d]=l.split('\t');x.additions+=Number(a)||0;x.deletions+=Number(d)||0;return x;},{additions:0,deletions:0}); const files=walk(p,{maxDepth:5,maxFiles:1500,ignore:['dist','build','.next','vendor','coverage'],accept:(f)=>{const s=stat(f);return(s?.size||0)<1e6&&/\.(js|mjs|cjs|ts|tsx|jsx|py|go|rs|html|css|md|json|yml|yaml|sql|sh)$/i.test(f)}});let lines=0;for(const f of files)try{lines+=fs.readFileSync(f,'utf8').split('\n').length}catch{} return {commits:n(['rev-list','--count','HEAD']),...changes,netChange:changes.additions-changes.deletions,filesMeasured:files.length,linesMeasured:lines}; }
const headline = (s) => [CONFIDENCE.confirmed, CONFIDENCE.strong].includes(s.attributionConfidence);
function efficiency(sessions, now = new Date()) { const end = new Date(now), start = new Date(end); start.setDate(start.getDate()-30); const previousStart = new Date(start); previousStart.setDate(previousStart.getDate()-30); const select=(from,to)=>sessions.filter(s=>headline(s)&&s.timestamp&&new Date(s.timestamp)>=from&&new Date(s.timestamp)<to); const current=select(start,end), previous=select(previousStart,start); const calc=(set)=>{const eligible=set.filter(s=>tokenActivity(s.tokens)>0);const tokens=eligible.reduce((a,s)=>a+tokenActivity(s.tokens),0);const cache=eligible.reduce((a,s)=>a+(s.tokens.cacheRead||0),0);const tools=set.reduce((a,s)=>a+s.tools,0);return {sessions:set.length,tokenSessions:eligible.length,tokensPerSession:eligible.length?tokens/eligible.length:null,toolsPerSession:set.length?tools/set.length:null,cacheReadRatio:tokens?cache/tokens:null,activeDays:new Set(set.map(s=>s.timestamp?.slice(0,10))).size};}; const c=calc(current),p=calc(previous); const comparison=(name)=>c.tokenSessions>=3&&p.tokenSessions>=3&&c[name]!=null&&p[name]!=null?{value:c[name],previous:p[name],change:(c[name]-p[name])/Math.abs(p[name]||1),comparable:true}:{value:c[name],comparable:false}; return {period:{from:start.toISOString(),to:end.toISOString()},current:c,previous:p,components:{tokensPerSession:comparison('tokensPerSession'),cacheReadRatio:comparison('cacheReadRatio'),toolsPerSession:c.sessions>=3&&p.sessions>=3?{value:c.toolsPerSession,previous:p.toolsPerSession,change:(c.toolsPerSession-p.toolsPerSession)/Math.abs(p.toolsPerSession||1),comparable:true}:{value:c.toolsPerSession,comparable:false}}}; }
export function derive(index) { const byProject=new Map(index.projects.map(p=>[p.id,{...p,sessions:[]}])); for(const s of index.sessions)if(s.projectId&&byProject.has(s.projectId)&&headline(s))byProject.get(s.projectId).sessions.push(s); const capEvents=index.capabilityUsageEvents||[]; const rawCapabilities=index.rawCapabilities||index.capabilities; const capabilities=groupCapabilities(rawCapabilities,capEvents); const projects=[...byProject.values()].map(p=>{const tokens=p.sessions.reduce((a,s)=>{addTokens(a,s.tokens);return a;},emptyTokens());return {...p,metrics:gitMetrics(p),sessionCount:p.sessions.length,agents:[...new Set(p.sessions.map(s=>s.agent))],hosts:[...new Set(p.sessions.map(s=>s.host||s.agent))],tokens,recentActivity:p.sessions.map(s=>s.timestamp).filter(Boolean).sort().at(-1)||p.git.lastCommitAt};}); const total=index.sessions.reduce((a,s)=>{a.sessions++;addTokens(a.tokens,s.tokens);a.tools+=s.tools;a.compactions+=s.compactions;return a;},{sessions:0,tools:0,compactions:0,tokens:emptyTokens()}); const diagnostics=index.diagnostics||{},now=Date.now(),today=new Date(now).toISOString().slice(0,10);const activity=index.sessions.filter(s=>s.timestamp?.slice(0,10)===today).sort((a,b)=>String(a.timestamp).localeCompare(String(b.timestamp))).map(s=>({timestamp:s.timestamp,agent:s.agent,host:s.host||s.agent,projectId:s.projectId,tools:s.tools}));const monitorEvents=index.sessions.filter(s=>s.timestamp&&now-new Date(s.timestamp).getTime()<=5*60*1000).map(s=>({timestamp:s.timestamp,agent:s.agent,tools:s.tools||0}));const result={...index,rawCapabilities,projects,capabilities,capabilityUsageEvents:capEvents,efficiency:efficiency(index.sessions),summary:{...total,activeProjects:projects.filter(p=>p.sessionCount||p.git.lastCommitAt).length,totalObservedTokenActivity:tokenActivity(total.tokens),agents:[...new Set(index.sessions.map(s=>s.agent))],hosts:[...new Set(index.sessions.map(s=>s.host||s.agent))],capabilityUses:capEvents.length,lastScanAt:new Date().toISOString(),diagnostics,activity,monitorEvents}};return {...result,maintenance:maintenanceGroups(capabilities),achievements:achievementsFor(result)}; }
export function scan(sources, previous=null) { const began=Date.now(),projects=discoverProjects(sources.projectsRoot),hostFor={Claude:'Claude Code',Codex:'Codex CLI',Cursor:'Cursor'},prior=new Map((previous?.sessions||[]).filter(s=>s.sourceFile).map(s=>[s.sourceFile,{...(s.tokens?s:{...s,tokens:{freshInput:s.usage?.input||0,output:s.usage?.output||0,cacheRead:s.usage?.cached||0,cacheCreation:0,reasoning:s.usage?.reasoning||0,other:0}}),host:s.host||hostFor[s.agent]||s.agent,attributedSkills:s.attributedSkills||[]}]));const claude=scanClaude(projects,sources.claudeRoot,prior),codex=scanCodex(projects,sources.codexRoot,prior),cursor=scanCursor(projects,sources.cursorRoot,prior);const sessions=[...claude.sessions,...codex.sessions,...cursor.sessions],rawCapabilities=[...discoverCapabilities(projects,sources),...discoverNativeAutomations()],allSignals=sessions.filter(s=>s.agent==='Claude').flatMap(s=>(s.attributedSkills||[]).map(x=>({sessionId:s.id,skill:x.skill,timestamp:x.timestamp||s.timestamp,sourceFile:s.sourceFile}))),newEvents=capabilityUsageEvents(allSignals,rawCapabilities,sessions);return derive({schemaVersion:4,metricVersion:METRIC_VERSION,sources,projects,sessions,rawCapabilities,capabilityUsageEvents:newEvents,editorHosts:[discoverVsCodeAI()],errors:[],diagnostics:{...claude.diagnostics,...codex.diagnostics,...cursor.diagnostics,durationMs:Date.now()-began}}); }
export function defaultSources(){return {projectsRoot:path.join(home,'Dropbox','Projects'),claudeRoot:path.join(home,'.claude','projects'),codexRoot:path.join(home,'.codex','sessions'),cursorRoot:path.join(home,'.cursor','projects')}};
