import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { METRIC_VERSION } from './core.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const publicAsset=filename=>path.join(root,'public','assets','agents',filename);
const dataUrl=filename=>`data:image/png;base64,${fs.readFileSync(publicAsset(filename)).toString('base64')}`;

export const PRIVACY={publicSafe:'Public-safe',userApproved:'User-approved',private:'Private',forbidden:'Forbidden'};
export const AGENT_ASSETS=Object.freeze({
  Claude:{filename:'claude.png',source:'Official Claude.app icon, copied locally from the installed native application.'},
  Codex:{filename:'codex.png',source:'Official Codex icon bundled with the installed ChatGPT/Codex application.'},
  Cursor:{filename:'cursor.png',source:'Official Cursor.app icon, copied locally from the installed native application.'}
});
const agentImages=Object.fromEntries(Object.entries(AGENT_ASSETS).map(([agent,asset])=>[agent,dataUrl(asset.filename)]));

const safeCapabilities=index=>index.capabilities.filter(c=>!c.isPrivate).map(c=>({name:c.name,type:c.type,description:c.description||null,descriptionSource:c.summaryKind,origin:c.origin.includes('Project')?'project-local':c.origin,scope:c.scope,usageCount:c.usageCount,compatibility:c.compatibleAgents||c.agents||[],components:c.components.map(x=>x.componentName),...(c.type==='Automation'?{agent:c.agent,trigger:c.trigger,behavior:c.behavior,implementation:c.implementation,portability:c.portability,active:Boolean(c.active),setupRecipe:c.setupRecipe}:{})}));
export function shareableStack(index){return {schemaVersion:'1.0',kind:'AI Development Dashboard Shareable Stack',generatedAt:new Date().toISOString(),agents:index.summary.agents.map(name=>({name})),capabilities:safeCapabilities(index),privacy:'No project names, paths, prompts, transcripts, credentials, environment values, or private capability metadata.'};}
export function manifest(index){return {schemaVersion:'1.0',kind:'ai-development-dashboard-stack-manifest',metricVersion:METRIC_VERSION,agents:index.summary.agents.map(name=>({name})),capabilities:safeCapabilities(index).map(c=>({name:c.name,type:c.type,description:c.description,origin:c.origin,scope:c.scope,compatibility:c.compatibility,...(c.type==='Automation'?{agent:c.agent,trigger:c.trigger,behavior:c.behavior,implementation:c.implementation,portability:c.portability,active:c.active,setupRecipe:c.setupRecipe}:{})})),importSupport:'design only — no install/import action is implemented'};}
export function privateInventory(index){return {warning:'PRIVATE — DO NOT SHARE. Paths are machine-specific; prompts, transcript bodies, credentials, secrets and environment values are excluded.',generatedAt:new Date().toISOString(),sources:index.sources,projects:index.projects.map(p=>({name:p.name,path:p.canonicalPath,git:p.git})),capabilities:index.capabilities.map(c=>({name:c.name,type:c.type,locations:c.installation,origin:c.origin,usageCount:c.usageCount}))};}
export function setupPrompt(index){const stack=shareableStack(index),capabilities=stack.capabilities.map(c=>`- ${c.name} (${c.type}; compatible: ${c.compatibility.join(', ')||'unknown'}): ${c.description||'No safe description available.'}${c.origin==='project-local'?' Source is local; do not assume it can be transferred.':''}${c.setupRecipe?` Safe setup recipe: ${c.setupRecipe}`:''}`).join('\n');return `You are preparing an AI development environment from a shared stack. Work safely and do not blindly install everything.\n\nFirst audit the target machine: inspect existing agents, skills, plugins, commands, MCP configuration, native automations, repositories, and editor integrations. Preserve working configuration. Compare the current environment with the shared stack below; identify already-installed, missing, different-version, conflicting, unsupported, and private/local-only items.\n\nFor each appropriate missing item, explain its source and compatibility before proposing a minimal install/adaptation plan. Avoid duplicates, never copy credentials, secrets, private prompts, private paths, raw conversations, or project data. Do not change global configuration without explicit approval. Validate each approved change afterwards and report what could not transfer safely.\n\nShared agents\n${stack.agents.map(a=>`- ${a.name}`).join('\n')}\n\nShared capabilities\n${capabilities}\n\nThis stack is a privacy-safe inventory generated at ${stack.generatedAt}. It is not a command to install every item.`;}

export const TOKEN_SHARE_DEFINITIONS={freshInput:{label:'Fresh input',color:'#FF2D78',explanation:'New input tokens observed in supported local records.'},output:{label:'Output',color:'#FBFAF8',explanation:'Output tokens observed in supported local records.'},cacheRead:{label:'Cache read',color:'#E69B7C',explanation:'Previously cached context read; not fresh input consumption.'},cacheCreation:{label:'Cache creation',color:'#79B8AA',explanation:'Context written to cache; distinct from cache reads.'}};
const sumTokens=sessions=>sessions.reduce((total,session)=>{for(const [key,value]of Object.entries(session.tokens||{}))total[key]=(total[key]||0)+(Number(value)||0);return total;},{});
const dayStart=now=>new Date(now.getFullYear(),now.getMonth(),now.getDate());
export function recapFor(index,period='month',now=new Date()){const dated=(index.sessions||[]).filter(s=>s.timestamp&&Number.isFinite(new Date(s.timestamp).getTime())),earliest=dated.map(s=>new Date(s.timestamp)).sort((a,b)=>a-b)[0]||null;let start,label,title;if(period==='today'){start=dayStart(now);label='Today';title='TODAY';}else if(period==='all'){start=earliest||now;label='Since tracking began';title='SINCE TRACKING BEGAN';}else{start=new Date(now.getFullYear(),now.getMonth(),1);label='This Month';title=new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(now).toUpperCase();period='month';}const sessions=dated.filter(s=>new Date(s.timestamp)>=start&&new Date(s.timestamp)<=now),knownAgents=index.summary?.agents?.length?index.summary.agents:[...new Set(dated.map(s=>s.agent))],agentSplit=knownAgents.map(agent=>({agent,sessions:sessions.filter(s=>s.agent===agent).length})),projectIds=new Set(sessions.map(s=>s.projectId).filter(Boolean)),usage=(index.capabilityUsageEvents||[]).filter(e=>e.timestamp&&new Date(e.timestamp)>=start&&new Date(e.timestamp)<=now),tokens=sumTokens(sessions);return {id:period,label,title,from:start.toISOString(),to:now.toISOString(),trackingStartedAt:earliest?.toISOString()||null,sessions,sessionCount:sessions.length,activeProjects:projectIds.size,agentSplit,capabilityUses:usage.length,tokens};}
export function publicMetricOptions(index,period='month',now=new Date()){const recap=recapFor(index,period,now),options=[];if(recap.activeProjects)options.push({id:'activeProjects',label:'Active projects',value:recap.activeProjects,available:true,family:'projects'});options.push({id:'sessions',label:'AI sessions',value:recap.sessionCount,available:true,family:'activity'});if(recap.agentSplit.some(agent=>agent.sessions>0))options.push({id:'agentSplit',label:'Agent session split',value:recap.agentSplit,available:true,family:'agents'});if(recap.capabilityUses)options.push({id:'capabilityUses',label:'Confirmed capability uses',value:recap.capabilityUses,available:true,family:'capabilities'});const allTokens=sumTokens(index.sessions||[]);for(const [id,definition]of Object.entries(TOKEN_SHARE_DEFINITIONS)){if(!(Number(allTokens[id])>0))continue;const value=Number(recap.tokens[id])||0,available=value>0;options.push({id,label:`${definition.label} tokens`,value:available?value:null,available,family:'tokens',definition:definition.explanation,...(!available?{unavailable:`No supported ${definition.label.toLowerCase()} token data for ${recap.label}.`}:{})});}const trend=index.efficiency?.components?.tokensPerSession;if(period==='month'&&trend?.comparable)options.push({id:'tokensPerSessionTrend',label:'Token activity per session trend',value:trend.change,available:true,family:'efficiency'});return {recap,options};}
export function storyCardsFor(recap,metrics){const ids=new Set(metrics.map(metric=>metric.id)),cards=[{id:'hero',label:recap.id==='today'?'Today':'Recap',metricIds:[...ids]}];if(ids.has('agentSplit'))cards.push({id:'agents',label:'Agent split',metricIds:['agentSplit']});if(metrics.some(metric=>metric.family==='tokens'))cards.push({id:'tokens',label:'Token composition',metricIds:metrics.filter(metric=>metric.family==='tokens').map(metric=>metric.id)});if(ids.has('activeProjects')||ids.has('sessions'))cards.push({id:'output',label:'Projects & sessions',metricIds:['activeProjects','sessions'].filter(id=>ids.has(id))});if(ids.has('capabilityUses')||ids.has('tokensPerSessionTrend'))cards.push({id:'progress',label:'Stack progress',metricIds:['capabilityUses','tokensPerSessionTrend'].filter(id=>ids.has(id))});return cards;}
export function createSnapshot(index,selection,format,snapshotsDir,period='month',visual={}){const {recap,options}=publicMetricOptions(index,period),allowed=new Map(options.map(metric=>[metric.id,metric])),metrics=(selection||[]).filter(id=>allowed.has(id)).map(id=>allowed.get(id));if(!metrics.length)throw new Error('Choose at least one supported public-safe metric.');const emphasis=['overview','agents','tokens'].includes(visual?.emphasis)?visual.emphasis:'overview',story={version:1,cards:storyCardsFor(recap,metrics),selected:emphasis==='agents'?'agents':emphasis==='tokens'?'tokens':'hero'},snapshot={id:crypto.randomUUID(),generatedAt:new Date().toISOString(),period:{id:recap.id,label:recap.label,title:recap.title,from:recap.from,to:recap.to,trackingStartedAt:recap.trackingStartedAt},metricDefinitionsVersion:METRIC_VERSION,privacy:PRIVACY.publicSafe,format,visual:{emphasis},story,metrics};fs.mkdirSync(snapshotsDir,{recursive:true});fs.writeFileSync(path.join(snapshotsDir,`${snapshot.id}.json`),JSON.stringify(snapshot,null,2));return snapshot;}

const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[char]));
const compact=value=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Math.round(Number(value)||0));
const metricText=metric=>metric.available===false?'Unavailable':metric.id==='tokensPerSessionTrend'?`${metric.value<0?'↓':'↑'} ${Math.abs(metric.value*100).toFixed(0)}%`:new Intl.NumberFormat('en').format(Math.round(Number(metric.value)||0));
const agentColor=agent=>({Claude:'#E69B7C',Codex:'#D7D0C5',Cursor:'#79B8AA'}[agent]||'#FF2D78');
export function agentMarkScale(value,max,{min=58,maxSize=260}={}){const count=Math.max(0,Number(value)||0),peak=Math.max(0,Number(max)||0);if(!count||!peak)return 0;return min+(maxSize-min)*Math.sqrt(count/peak);}
export function agentAsset(agent){return agentImages[agent]||null;}
const mark=(agent,x,y,size,opacity=1)=>{const href=agentAsset(agent);if(!href)return `<circle cx="${x}" cy="${y}" r="${size/2}" fill="${agentColor(agent)}" opacity="${opacity}"/>`;return `<image href="${href}" x="${x-size/2}" y="${y-size/2}" width="${size}" height="${size}" opacity="${opacity}" preserveAspectRatio="xMidYMid meet"/>`;};
const metricById=(metrics,id)=>metrics.find(metric=>metric.id===id);
const label=(text,x,y,size=18,color='#A39D97')=>`<text x="${x}" y="${y}" fill="${color}" font-family="Arial,sans-serif" font-size="${size}" letter-spacing="2.5">${esc(text.toUpperCase())}</text>`;
const rule=(x,y,width)=>`<line x1="${x}" y1="${y}" x2="${x+width}" y2="${y}" stroke="#514C47" stroke-width="2"/>`;
function stat(metric,x,y,{size=96,width=250}={}){if(!metric)return '';const unavailable=metric.available===false;return `<g>${rule(x,y,width)}${label(metric.label,x,y+34,16)}<text x="${x}" y="${y+size+48}" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="${size}">${esc(metricText(metric))}</text>${unavailable?`<text x="${x}" y="${y+size+78}" fill="#8F8A85" font-family="Arial,sans-serif" font-size="14">${esc(metric.unavailable)}</text>`:''}</g>`;}
function agentField(metric,{x,y,width,height,large=false}){if(!metric)return '';const values=metric.value||[],total=values.reduce((sum,item)=>sum+item.sessions,0),peak=Math.max(0,...values.map(item=>item.sessions)),lead=values.find(item=>item.sessions===peak),leadPercent=total?Math.round(peak/total*100):0,count=Math.max(1,values.length),cell=width/count,maxSize=Math.min(height*(large?.54:.38),cell*(large?.78:.54),large?300:180),hero=large&&lead?.sessions?`<text x="${x}" y="${y+175}" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="132">${leadPercent}%</text>${label(`${lead.agent} session share`,x,y+212,18,'#E69B7C')}`:'',markY=large?.48:.45,labelY=large?.66:.78,countY=large?.76:.9;return `<g>${label('Observed agent split',x,y+25,17,'#FF2D78')}${hero}${values.map((item,index)=>{const percent=total?Math.round(item.sessions/total*100):0,size=agentMarkScale(item.sessions,peak,{min:maxSize*.35,maxSize}),visible=size||maxSize*.22,cx=x+cell*(index+.5),cy=y+height*markY;return `${mark(item.agent,cx,cy,visible,item.sessions?1:.2)}<text x="${cx}" y="${y+height*labelY}" text-anchor="middle" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="${large?30:22}">${esc(item.agent)}</text><text x="${cx}" y="${y+height*countY}" text-anchor="middle" fill="${agentColor(item.agent)}" font-family="Arial,sans-serif" font-size="${large?24:18}">${item.sessions} · ${percent}%</text>`;}).join('')}</g>`;}
function tokenField(metrics,{x,y,width,height}){const selected=metrics.filter(metric=>metric.family==='tokens'),available=selected.filter(metric=>metric.available!==false&&Number(metric.value)>0),total=available.reduce((sum,metric)=>sum+Number(metric.value),0);if(!selected.length)return '';let cursor=x;const barY=y+65,barHeight=Math.max(18,height*.06),segments=available.map(metric=>{const segmentWidth=total?width*Number(metric.value)/total:0,svg=`<rect x="${cursor}" y="${barY}" width="${segmentWidth}" height="${barHeight}" fill="${TOKEN_SHARE_DEFINITIONS[metric.id]?.color||'#FF2D78'}"/>`;cursor+=segmentWidth;return svg;}).join('');const columns=selected.length>2?2:selected.length,cellWidth=width/Math.max(1,columns);return `<g>${label('Observed token composition',x,y+24,17,'#FF2D78')}<text x="${x+width}" y="${y+24}" text-anchor="end" fill="#8F8A85" font-family="Arial,sans-serif" font-size="15">Cache activity ≠ fresh consumption</text><rect x="${x}" y="${barY}" width="${width}" height="${barHeight}" rx="${barHeight/2}" fill="#2A2826"/>${segments}${selected.map((metric,index)=>{const col=index%columns,row=Math.floor(index/columns),left=x+col*cellWidth,top=y+barHeight+55+row*96,color=TOKEN_SHARE_DEFINITIONS[metric.id]?.color||'#FF2D78',value=metric.available===false?metric.unavailable:compact(metric.value);return `<rect x="${left}" y="${top-13}" width="10" height="10" rx="5" fill="${color}" opacity="${metric.available===false?.35:1}"/><text x="${left+20}" y="${top}" fill="#BEB9B4" font-family="Arial,sans-serif" font-size="18">${esc(metric.label)}</text><text x="${left+20}" y="${top+34}" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="31">${esc(value)}</text>`;}).join('')}</g>`;}
function cardsPoster(snapshot,area){const sessions=metricById(snapshot.metrics,'sessions'),projects=metricById(snapshot.metrics,'activeProjects'),capabilities=metricById(snapshot.metrics,'capabilityUses'),agents=metricById(snapshot.metrics,'agentSplit'),hasStats=Boolean(sessions||projects||capabilities);if(!hasStats)return tokenField(snapshot.metrics,area);return `<g>${sessions?`<text x="${area.x}" y="${area.y+210}" fill="#FBFAF8" font-family="Arial,sans-serif" font-size="${area.width>1200?260:210}" font-weight="700">${esc(metricText(sessions))}</text>${label('AI sessions',area.x,area.y+248,22,'#FF2D78')}`:''}${projects?stat(projects,area.x,area.y+330,{size:86,width:area.width*.4}):''}${capabilities?stat(capabilities,area.x+area.width*.5,area.y+330,{size:86,width:area.width*.4}):''}${agentField(agents,{x:area.x,y:area.y+510,width:area.width,height:area.height-510,large:false})}</g>`;}
export function shareCardSvg(snapshot){const sizes={'1:1':[1080,1080],'4:5':[1080,1350],'9:16':[1080,1920],'16:9':[1920,1080]},[width,height]=sizes[snapshot.format]||sizes['1:1'],wide=snapshot.format==='16:9',story=snapshot.format==='9:16',margin=wide?94:72,bodyTop=story?285:wide?215:255,bodyHeight=height-bodyTop-110,period=snapshot.period||{},title=period.title||'MY DEV STORY',tag=period.id==='today'?'LIVE DEVELOPMENT RECAP':period.id==='all'?'DEVELOPER PROFILE':'MONTHLY DEVELOPMENT RECAP',tracking=period.id==='all'&&period.trackingStartedAt?`Tracking since ${new Intl.DateTimeFormat('en',{month:'short',year:'numeric'}).format(new Date(period.trackingStartedAt))}`:'Observed local development activity',agents=metricById(snapshot.metrics,'agentSplit'),focus=snapshot.visual?.emphasis||'overview',area={x:margin,y:bodyTop,width:width-margin*2,height:bodyHeight};let body;if(focus==='agents'&&agents)body=agentField(agents,{...area,large:true});else if(focus==='tokens')body=`${tokenField(snapshot.metrics,{...area,height:area.height*.52})}${agentField(agents,{x:area.x,y:area.y+area.height*.6,width:area.width,height:area.height*.4,large:false})}`;else body=cardsPoster(snapshot,area);return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(period.label||'Development')} AI development recap"><rect width="100%" height="100%" fill="#141413"/><rect width="100%" height="${Math.max(11,height*.012)}" fill="#FF2D78"/><path d="M ${width*.68} 0 A ${Math.min(width,height)*.31} ${Math.min(width,height)*.31} 0 0 1 ${width} ${height*.3}" fill="none" stroke="#FF2D78" stroke-width="2" opacity=".18"/>${label(tag,margin,story?90:75,story?23:20,'#FF2D78')}<text x="${margin}" y="${story?185:145}" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="${story?62:wide?64:52}">${esc(title)}</text><text x="${margin}" y="${story?230:180}" fill="#A39D97" font-family="Arial,sans-serif" font-size="${story?19:17}">${esc(tracking)}</text>${body}<line x1="${margin}" x2="${width-margin}" y1="${height-82}" y2="${height-82}" stroke="#514C47"/><text x="${margin}" y="${height-42}" fill="#8F8A85" font-family="Arial,sans-serif" font-size="17">AI Development Dashboard · local-first · public-safe metrics</text></svg>`;}
