import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { METRIC_VERSION } from './core.js';

export const PRIVACY = { publicSafe:'Public-safe', userApproved:'User-approved', private:'Private', forbidden:'Forbidden' };
const safeCapabilities = (index) => index.capabilities.filter(c => !c.isPrivate).map(c => ({ name:c.name, type:c.type, description:c.description || null, descriptionSource:c.summaryKind, origin:c.origin.includes('Project')?'project-local':c.origin, usageCount:c.usageCount, compatibility:c.agents||[], components:c.components.map(x=>x.componentName) }));
export function shareableStack(index) { return { schemaVersion:'1.0', kind:'AI Development Dashboard Shareable Stack', generatedAt:new Date().toISOString(), agents:index.summary.agents.map(name=>({name})), capabilities:safeCapabilities(index), privacy:'No project names, paths, prompts, transcripts, credentials, environment values, or private capability metadata.' }; }
export function manifest(index) { return { schemaVersion:'1.0', kind:'ai-development-dashboard-stack-manifest', metricVersion:METRIC_VERSION, agents:index.summary.agents.map(name=>({name})), capabilities:safeCapabilities(index).map(c=>({name:c.name,type:c.type,description:c.description,origin:c.origin,compatibility:c.compatibility})), importSupport:'design only — no install/import action is implemented' }; }
export function privateInventory(index) { return { warning:'PRIVATE — DO NOT SHARE. Paths are machine-specific; prompts, transcript bodies, credentials, secrets and environment values are excluded.', generatedAt:new Date().toISOString(), sources:index.sources, projects:index.projects.map(p=>({name:p.name,path:p.canonicalPath,git:p.git})), capabilities:index.capabilities.map(c=>({name:c.name,type:c.type,locations:c.installation,origin:c.origin,usageCount:c.usageCount})) }; }
export function setupPrompt(index) { const stack=shareableStack(index); const capabilities=stack.capabilities.map(c=>`- ${c.name} (${c.type}; compatible: ${c.compatibility.join(', ')||'unknown'}): ${c.description||'No safe description available.'}${c.origin==='project-local'?' Source is local; do not assume it can be transferred.':''}`).join('\n'); return `You are preparing an AI development environment from a shared stack. Work safely and do not blindly install everything.\n\nFirst audit the target machine: inspect existing agents, skills, plugins, commands, MCP configuration, repositories, and editor integrations. Preserve working configuration. Compare the current environment with the shared stack below; identify already-installed, missing, different-version, conflicting, unsupported, and private/local-only items.\n\nFor each appropriate missing item, explain its source and compatibility before proposing a minimal install/adaptation plan. Avoid duplicates, never copy credentials, secrets, private prompts, private paths, raw conversations, or project data. Do not change global configuration without explicit approval. Validate each approved change afterwards and report what could not transfer safely.\n\nShared agents\n${stack.agents.map(a=>`- ${a.name}`).join('\n')}\n\nShared capabilities\n${capabilities}\n\nThis stack is a privacy-safe inventory generated at ${stack.generatedAt}. It is not a command to install every item.`; }
const sumTokens=sessions=>sessions.reduce((total,session)=>{for(const [key,value]of Object.entries(session.tokens||{}))total[key]=(total[key]||0)+(Number(value)||0);return total;},{});
const dayStart=now=>new Date(now.getFullYear(),now.getMonth(),now.getDate());
export function recapFor(index, period='month', now=new Date()) { const dated=(index.sessions||[]).filter(s=>s.timestamp&&Number.isFinite(new Date(s.timestamp).getTime())), earliest=dated.map(s=>new Date(s.timestamp)).sort((a,b)=>a-b)[0]||null; let start,label,title; if(period==='today'){start=dayStart(now);label='Today';title='TODAY';}else if(period==='all'){start=earliest||now;label='Since tracking began';title='SINCE TRACKING BEGAN';}else{start=new Date(now.getFullYear(),now.getMonth(),1);label='This Month';title=new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(now).toUpperCase();period='month';} const sessions=dated.filter(s=>new Date(s.timestamp)>=start&&new Date(s.timestamp)<=now),agentSplit=[...new Set(sessions.map(s=>s.agent))].map(agent=>({agent,sessions:sessions.filter(s=>s.agent===agent).length})),projectIds=new Set(sessions.map(s=>s.projectId).filter(Boolean)),usage=(index.capabilityUsageEvents||[]).filter(e=>e.timestamp&&new Date(e.timestamp)>=start&&new Date(e.timestamp)<=now),tokens=sumTokens(sessions); return {id:period,label,title,from:start.toISOString(),to:now.toISOString(),trackingStartedAt:earliest?.toISOString()||null,sessions,sessionCount:sessions.length,activeProjects:projectIds.size,agentSplit,capabilityUses:usage.length,tokens}; }
export function publicMetricOptions(index, period='month', now=new Date()) { const recap=recapFor(index,period,now),options=[]; if(recap.activeProjects)options.push({id:'activeProjects',label:'Active projects',value:recap.activeProjects}); options.push({id:'sessions',label:'AI sessions',value:recap.sessionCount}); if(recap.agentSplit.length)options.push({id:'agentSplit',label:'Agent split',value:recap.agentSplit}); if(recap.capabilityUses)options.push({id:'capabilityUses',label:'Confirmed capability uses',value:recap.capabilityUses}); if(recap.tokens.freshInput)options.push({id:'freshInput',label:'Fresh input tokens',value:recap.tokens.freshInput}); if(recap.tokens.output)options.push({id:'output',label:'Output tokens',value:recap.tokens.output}); const e=index.efficiency?.components?.tokensPerSession;if(period==='month'&&e?.comparable)options.push({id:'tokensPerSessionTrend',label:'Token activity per session trend',value:e.change}); return {recap,options}; }
export function createSnapshot(index, selection, format, snapshotsDir, period='month') { const {recap,options}=publicMetricOptions(index,period),allowed=new Map(options.map(m=>[m.id,m])); const metrics=(selection||[]).filter(id=>allowed.has(id)).map(id=>allowed.get(id)); if(!metrics.length) throw new Error('Choose at least one supported public-safe metric.'); const snapshot={id:crypto.randomUUID(),generatedAt:new Date().toISOString(),period:{id:recap.id,label:recap.label,title:recap.title,from:recap.from,to:recap.to,trackingStartedAt:recap.trackingStartedAt},metricDefinitionsVersion:METRIC_VERSION,privacy:PRIVACY.publicSafe,format,metrics}; fs.mkdirSync(snapshotsDir,{recursive:true}); fs.writeFileSync(path.join(snapshotsDir,`${snapshot.id}.json`),JSON.stringify(snapshot,null,2)); return snapshot; }
const esc=(s)=>String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
function metricText(m){if(m.id==='agentSplit')return m.value.map(x=>`${x.agent} ${x.sessions}`).join(' · ');if(m.id==='tokensPerSessionTrend')return `${m.value<0?'↓':'↑'} ${Math.abs(m.value*100).toFixed(0)}%`;if(typeof m.value==='number')return new Intl.NumberFormat().format(Math.round(m.value));return String(m.value)}
export function shareCardSvg(snapshot) { const sizes={'1:1':[1080,1080],'4:5':[1080,1350],'9:16':[1080,1920],'16:9':[1920,1080]},[w,h]=sizes[snapshot.format]||sizes['1:1'],story=snapshot.format==='9:16',periodTitle=snapshot.period?.title||'MY DEV STORY'; const rows=snapshot.metrics.slice(0,4).map((m,i)=>`<text x="80" y="${story?480+i*230:290+i*155}" fill="#bebcb9" font-family="Arial,sans-serif" font-size="${story?27:28}" letter-spacing="3">${esc(m.label.toUpperCase())}</text><text x="80" y="${story?560+i*230:355+i*155}" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="${story?70:58}">${esc(metricText(m))}</text>`).join(''); return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="#141413"/><rect x="0" y="0" width="16" height="100%" fill="#FF2D78"/><circle cx="${w*.84}" cy="${story?h*.16:h*.18}" r="${Math.min(w,h)*.20}" fill="#FF2D78" opacity=".12"/><text x="80" y="110" fill="#FF2D78" font-family="Arial,sans-serif" font-size="30" letter-spacing="6">AI DEVELOPMENT</text><text x="80" y="${story?250:175}" fill="#FBFAF8" font-family="Arial,sans-serif" font-weight="700" font-size="${story?64:52}">${esc(periodTitle)}</text>${rows}<line x1="80" x2="${w-80}" y1="${h-100}" y2="${h-100}" stroke="#77736f" opacity=".5"/><text x="80" y="${h-55}" fill="#bebcb9" font-family="Arial,sans-serif" font-size="24">Local-first · shared metrics only</text></svg>`; }
